### PR TITLE
docs: ✏️ Added instruction for "cy.waitUntil is undefined" error

### PR DESCRIPTION
**Pull request by john20xdoe**

### CODE REVIEW

**Comment by NoriSte** [comment]
Please, update the commit message to 

docs: ✏️ Added instruction for "cy.waitUntil is undefined" error

accordingly to [semver](https://semver.org/) and [commitizen](https://github.com/commitizen/cz-cli). Then I'll merge it 😊

Big thanks @john20xdoe 😊

**Comment by john20xdoe** [comment]
There seems to be no way to edit the commit message directly. Will cancel and retry agian later.

**Comment by NoriSte** [comment]
Did me with a squash, thank you so much @john20xdoe ❤️

**Pull request merged**
