### PR TITLE
Fixes TS definition for logger and updates script for running locally

### PR DESCRIPTION
**Pull request by sweir27**
👋 Hi there!

We've been happily using this library in our integration testing repository (thanks!).

After upgrading to the latest version to get the benefits of more verbose logging, I noticed that there was a TypeScript issue in the declaration file. 
```
node_modules/cypress-wait-until/index.d.ts:13:13 - error TS7051: Parameter has a name but no type. Did you mean 'arg0: WaitUntilLog'?

13   logger?: (WaitUntilLog) => any;
               ~~~~~~~~~~~~

Found 1 error.
```

Following the `Contributing` instructions in the README, I also noticed/fixed an error in the `cypress-run.js` script.

### CODE REVIEW

**Comment by NoriSte** [comment]
@all-contributors please add @sweir27 for bug and code

**Comment by NoriSte** [comment]
Thank you so much @sweir27 and sorry for the long delay 😉 in minutes it should be on NPM, I'll check it out

**Comment by sweir27** [comment]
@NoriSte Thank you! (And nice param rename 😄)

**Pull request merged**
